apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
      - name: uptime-kuma
        image: harbor.enersys.io/enersys/uptime-kuma:${TAG}
        ports:
        - containerPort: 3001
        env:
        - name: "DB_TYPE"
          value: "sqlite"
        - name: "DB_SQLITE_FILE"
          value: "/app/data/uptime-kuma.sqlite"
        volumeMounts:
        - name: uptime-kuma-data
          mountPath: /app/data
      volumes:
      - name: uptime-kuma-data
        persistentVolumeClaim:
          claimName: uptime-kuma-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: uptime-kuma