services:
  ssl-check:
    build: .
    volumes:
      - ssl-log:/var/log
    restart: always
    depends_on:
      - promtail

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /etc/promtail/promtail.yaml:/etc/promtail/promtail.yaml # เชื่อมโยงไฟล์คอนฟิก
      - /var/log:/var/log # เชื่อมโยงไดเรกทอรี log ถ้าต้องการ
    command: -config.file=/etc/promtail/promtail.yaml # ตั้งค่าเส้นทางคอนฟิก

  loki:
    image: grafana/loki:2.8.2
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki

volumes:
  ssl-log:
