apiVersion: batch/v1
kind: CronJob
metadata:
  name: ssl-check-job
spec:
  schedule: "*/1 * * * *"  # Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ssl-check-container
            image: alpine:3.20.3   # Use a lightweight Alpine Linux image
            command: ["/bin/sh", "-c", "/scripts/ssl_check.sh"]  # Specify the shell script to run
            volumeMounts:
            - name: ssl-check-volume
              mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
          - name: ssl-check-volume
            configMap:
              name: ssl-check-configmap  # Reference to ConfigMap where the script is stored
              defaultMode: 0755
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
