version: '3.3'

services:
  uptime-kuma:
    build:  # ใช้ build แทนการใช้ image
      context: .  # กำหนด context ให้เป็นโฟลเดอร์ปัจจุบัน
      dockerfile: Dockerfile  # เปลี่ยนชื่อ Dockerfile ได้ถ้าต้องการ
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always