apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: cattle-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
      - name: uptime-kuma
        image: horborlab.enersys.io/lab1/uptime:0.1
        ports:
        - containerPort: 3001
        env:
        - name: DB_TYPE
          value: sqlite
        - name: DB_SQLITE_FILE
          value: /app/data/uptime-kuma.sqlite
