name: Release

on:
  push:
    tags:
      - '**'

env:
  REGISTRY: harbor.enersys.io
  IMAGE_NAME: uptime-kuma
  PROJECT_ID: enersys

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Fetch all tags
        run: git fetch --force --tags
  
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm run setup

      - name: Build Docker Image
        run: |
            DOCKER_BUILDKIT=1 docker build --platform linux/amd64 -t harbor.enersys.io/enersys/uptime-kuma:latest -f Dockerfile .              
  release:
    permissions:
      contents: write
      packages: write
      id-token: write
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }} 
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}
    
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{env.PROJECT_ID}}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set environment variable
        run: echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV


      - name: Substitute environment variables in Kubernetes manifest
        run: |
          envsubst < deployment.yaml > .manifests/deployment.yaml

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}    

